version: '3.8'
services:
  teapot-bot:
    build: .
    environment:
      - TELEGRAM_TOKEN=${TELEGRAM_TOKEN}
    volumes:
      - .:/app
    restart: unless-stopped
    networks:
      - teapot-net

networks:
  teapot-net:
    driver: bridge
    attachable: true